/**
 * @file investmentAgent.js
 * @description LangGraph orchestrator representing the AI Investment Research Agent workflow.
 */

import { StateGraph, Annotation } from '@langchain/langgraph';
import { searchCompanies, resolveTicker } from '../services/fmp/company.js';
import companyTool from './tools/company.tool.js';
import financialTool from './tools/financial.tool.js';
import ratioTool from './tools/ratio.tool.js';
import stockTool from './tools/stock.tool.js';
import eventsTool from './tools/events.tool.js';
import newsTool from './tools/news.tool.js';
import newsFilterTool from './tools/newsFilter.tool.js';
import investmentAnalysisTool from './tools/investmentAnalysis.tool.js';

/**
 * State definition for the StateGraph.
 * Stores information gathered at each step of the pipeline.
 */
export const AgentState = Annotation.Root({
  companyQuery: Annotation,    // The input query (e.g., "NVIDIA" or "NVDA")
  symbol: Annotation,          // Resolved ticker symbol (e.g., "NVDA")
  companyName: Annotation,     // Resolved company name (e.g., "NVIDIA Corporation")
  profile: Annotation,         // Company profile from FMP
  financials: Annotation,      // Financial statements (Income statement, Balance sheet, Cash flow)
  ratios: Annotation,          // Financial ratios and metrics
  stock: Annotation,           // Stock quotes and historical metrics
  events: Annotation,          // Earnings calendar/corporate events
  news: Annotation,            // Raw news articles
  filteredNews: Annotation,    // News filtered by AI filter service
  analysis: Annotation,        // Final investment analysis generated by AI
});

/**
 * Node 1: Resolves symbol/name and fetches Company Profile.
 */
async function companyNode(state) {
  try {
    const query = state.companyQuery ? state.companyQuery.trim() : '';

    if (!query) {
      throw new Error('A company name or ticker symbol query is required to start the agent.');
    }

    // Call resolveTicker to dynamically resolve the ticker symbol
    const targetSymbol = await resolveTicker(query);

    // Call the company tool
    const profileData = await companyTool.invoke({ symbol: targetSymbol });
    let profile = null;

    if (Array.isArray(profileData) && profileData.length > 0) {
      profile = profileData[0];
    } else if (profileData && typeof profileData === 'object' && !Array.isArray(profileData)) {
      profile = profileData;
    }

    if (!profile) {
      throw new Error(`Company profile not found for symbol "${targetSymbol}".`);
    }

    return {
      symbol: targetSymbol,
      companyName: profile.companyName || targetSymbol,
      profile,
    };
  } catch (error) {
    throw new Error(`[Node: Company] Failed: ${error.message}`);
  }
}

/**
 * Node 2: Fetches Financial Statements.
 */
async function financialNode(state) {
  try {
    const data = await financialTool.invoke({ symbol: state.symbol });
    return { financials: data };
  } catch (error) {
    throw new Error(`[Node: Financial] Failed: ${error.message}`);
  }
}

/**
 * Node 3: Fetches Financial Ratios.
 */
async function ratiosNode(state) {
  try {
    const data = await ratioTool.invoke({ symbol: state.symbol });
    return { ratios: data };
  } catch (error) {
    throw new Error(`[Node: Ratios] Failed: ${error.message}`);
  }
}

/**
 * Node 4: Fetches Stock price data.
 */
async function stockNode(state) {
  try {
    const data = await stockTool.invoke({ symbol: state.symbol });
    return { stock: data };
  } catch (error) {
    throw new Error(`[Node: Stock] Failed: ${error.message}`);
  }
}

/**
 * Node 5: Fetches scheduled earnings events.
 */
async function eventsNode(state) {
  try {
    const data = await eventsTool.invoke({ symbol: state.symbol });
    return { events: data };
  } catch (error) {
    console.error(`[Node: Events] Warning (skipping): ${error.message}`);
    return { events: [] };
  }
}

/**
 * Node 6: Fetches latest news articles.
 */
async function newsNode(state) {
  try {
    const data = await newsTool.invoke({ symbol: state.symbol });
    return { news: data };
  } catch (error) {
    console.error(`[Node: News] Warning (skipping): ${error.message}`);
    return { news: [] };
  }
}

/**
 * Node 7: Filters news using AI newsFilter service.
 */
async function newsFilterNode(state) {
  try {
    const result = await newsFilterTool.invoke({
      companyName: state.companyName,
      newsArticles: state.news || [],
    });
    return { filteredNews: result.filteredNews };
  } catch (error) {
    console.error(`[Node: News Filter] Warning (skipping): ${error.message}`);
    return { filteredNews: [] };
  }
}

/**
 * Node 8: Performs investment analysis and compiles recommendation.
 */
async function analysisNode(state) {
  try {
    const researchPayload = {
      profile: state.profile,
      financials: state.financials,
      ratios: state.ratios,
      stock: state.stock,
      events: state.events,
      news: state.filteredNews || [],
    };

    const analysisResult = await investmentAnalysisTool.invoke({ research: researchPayload });
    return { analysis: analysisResult };
  } catch (error) {
    throw new Error(`[Node: Investment Analysis] Failed: ${error.message}`);
  }
}

// Construct sequential LangGraph flow
const workflow = new StateGraph(AgentState)
  .addNode('fetchCompany', companyNode)
  .addNode('fetchFinancials', financialNode)
  .addNode('fetchRatios', ratiosNode)
  .addNode('fetchStock', stockNode)
  .addNode('fetchEvents', eventsNode)
  .addNode('fetchNews', newsNode)
  .addNode('filterNews', newsFilterNode)
  .addNode('analyzeInvestment', analysisNode)
  .addEdge('__start__', 'fetchCompany')
  .addEdge('fetchCompany', 'fetchFinancials')
  .addEdge('fetchFinancials', 'fetchRatios')
  .addEdge('fetchRatios', 'fetchStock')
  .addEdge('fetchStock', 'fetchEvents')
  .addEdge('fetchEvents', 'fetchNews')
  .addEdge('fetchNews', 'filterNews')
  .addEdge('filterNews', 'analyzeInvestment')
  .addEdge('analyzeInvestment', '__end__');

export const investmentAgent = workflow.compile();
export default investmentAgent;
